export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_ERROR = "ORDER_PAY_ERROR";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_ERROR = "ORDER_DELIVER_ERROR";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_ERROR = "ORDER_DETAILS_ERROR";

export const ORDER_MINE_LIST_REQUEST = "ORDER_MINE_LIST_REQUEST";
export const ORDER_MINE_LIST_SUCCESS = "ORDER_MINE_LIST_SUCCESS";
export const ORDER_MINE_LIST_ERROR = "ORDER_MINE_LIST_ERROR";

export const ORDER_USER_LIST_REQUEST = "ORDER_USER_LIST_REQUEST";
export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";
export const ORDER_USER_LIST_ERROR = "ORDER_USER_LIST_ERROR";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_ERROR = "ORDER_DELETE_ERROR";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";

