export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const DETAILS_USER_REQUEST = "DETAILS_USER_REQUEST";
export const DETAILS_USER_SUCCESS = "DETAILS_USER_SUCCESS";
export const DETAILS_USER_ERROR = "DETAILS_USER_ERROR";
export const DETAILS_USER_RESET = "DETAILS_USER_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_ERROR = "USER_UPDATE_PROFILE_ERROR";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_ERROR = "LIST_USER_ERROR";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const LIST_TOPSELLER_USER_REQUEST = "LIST_TOPSELLER_USER_REQUEST";
export const LIST_TOPSELLER_USER_SUCCESS = "LIST_TOPSELLER_USER_SUCCESS";
export const LIST_TOPSELLER_USER_ERROR = "LIST_TOPSELLER_USER_ERROR";

export const CONFIRM_USER_REGISTER_REQUEST = "CONFIRM_USER_REGISTER_REQUEST";
export const CONFIRM_USER_REGISTER_ERROR = "CONFIRM_USER_REGISTER_ERROR";
export const CONFIRM_USER_REGISTER_SUCCESS = "CONFIRM_USER_REGISTER_SUCCESS";